/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],*/

  // But you can create a sidebar manually
  
   Docs: [
     '互联网计算机 wiki',
     {
       type: 'category',
       label: 'Guides',
       collapsible: true,
       collapsed: false,
       items: [
         'wiki/ICP代币持有者、质押者和神经元持有者的互联网计算机',
         {
           type: 'category',
           label: 'Docs',
           items: ['wiki/ICP代币持有者、质押者和神经元持有者的互联网计算机/ICP代币', 'wiki/ICP代币持有者、质押者和神经元持有者的互联网计算机/互联网计算机代币持有者、投资者和神经元持有者'],
         },
       ],
     },
   ],
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
